spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javatest?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jdbc:
    template:
      query-timeout: 3 # 查询超时时间，以秒为单位

# mybatis
mybatis:
  type-aliases-package: com.joush.entities
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名